#!/usr/bin/env bash
#
# A wizard -- walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# --------------------------------------------------------------------------
# Wizard library -- delightful, consistent UX. Identical across every wizard.
# --------------------------------------------------------------------------

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
ENV_EXAMPLE=".scratch/mini-kimi-k3-replication/.env.example"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do, for example gh missing

# _clear -- wipe the terminal so only the current step is on screen. No-op when
# output is not a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" -- opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser and operator actions; this wizard prints the\n' "$DIM"
  printf '  checks to run and captures local launch settings. Stop any time with\n'
  printf '  Ctrl-C and re-run later -- it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" -- clear the screen, then announce a stage and show progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s> Stage %s/%s - %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s*%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s! %s%s\n' "$RED" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %sopening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "could not open a browser -- visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "could not open a browser -- visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %swrote%s %s -> %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sset%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name -- gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sset%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name -- gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  Setup summary%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# --------------------------------------------------------------------------
# STAGES -- Mini Kimi-K3 full-launch unblock workflow.
# --------------------------------------------------------------------------

TOTAL_STAGES=5

REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
cd "$REPO_ROOT"

RUN_ID="${RUN_ID:-mini-kimi-k3-r1-local}"
ATTEMPT_ID="${ATTEMPT_ID:-attempt-guarded-current-003}"
PREFLIGHT_REPORT="experiments/mini_kimi_k3/results/preflight.json"
COMPLETION_REPORT="experiments/mini_kimi_k3/reports/completion-audit.json"
REMOTE_READINESS_REPORT="experiments/mini_kimi_k3/reports/stage1-remote-readiness.json"
CORPUS_AUDIT_REPORT="experiments/mini_kimi_k3/reports/r1-corpus-plan-audit.json"
CORPUS_DISK_READINESS_REPORT="experiments/mini_kimi_k3/reports/corpus-disk-readiness.json"
STAGE1_INPUT_INSPECTION_REPORT="experiments/mini_kimi_k3/reports/source-inputs-inspection.json"
R1_SMOKE_REPORT="experiments/mini_kimi_k3/results/r1_training_smoke.json"

run_rootfs() {
  scripts/rootfs/enter_rootfs.sh -- bash -lc "cd /workspace/torchtitan && $*"
}

run_networked_rootfs() {
  TORCHTITAN_ROOTFS_NETWORK=networked scripts/rootfs/enter_rootfs.sh -- bash -lc "cd /workspace/torchtitan && $*"
}

remote_env_arg() {
  [[ -f "$ENV_FILE" ]] || return 0
  printf ' --env-file %q' "$ENV_FILE"
}

stage1_input_inspection_arg() {
  [[ -f "$STAGE1_INPUT_INSPECTION_REPORT" ]] || return 0
  printf ' --stage1-input-inspection-report %q' "$STAGE1_INPUT_INSPECTION_REPORT"
}

banner "Mini Kimi-K3 full-launch unblock"

stage "Inspect Current Gates"
say "This stage refreshes non-GPU, non-spendful gate reports. It does not launch training or Modal ingestion."
run_networked_rootfs "./experiments/mini_kimi_k3/run.sh stage1-remote-readiness$(remote_env_arg) --report $REMOTE_READINESS_REPORT" || true
run_rootfs "./experiments/mini_kimi_k3/run.sh audit-r1-corpus-plan --manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --corpus-plan experiments/mini_kimi_k3/reports/r1-corpus-plan.json --report $CORPUS_AUDIT_REPORT" || true
run_rootfs "./experiments/mini_kimi_k3/run.sh corpus-disk-readiness --corpus-plan experiments/mini_kimi_k3/reports/r1-corpus-plan.json --target-path experiments/mini_kimi_k3/data/tokens --report $CORPUS_DISK_READINESS_REPORT --overhead-fraction 0.20" || true
run_rootfs "./experiments/mini_kimi_k3/run.sh preflight --mode full --token-manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --evidence-results-root experiments/mini_kimi_k3/results --run-id $RUN_ID --attempt-id $ATTEMPT_ID --oracle-root experiments/mini_kimi_k3/assets/mini-kimi-k3-vizuara --forward-oracle-report .cache/trae-mini-k3-trainer/forward_oracle_r1_candidate_cuda.json --launch-backend-report .cache/trae-mini-k3-trainer/launch_backend_r1_candidate_cuda.json --r1-training-smoke-report $R1_SMOKE_REPORT --r1-corpus-plan-audit-report $CORPUS_AUDIT_REPORT --corpus-disk-readiness-report $CORPUS_DISK_READINESS_REPORT --stage1-source-resolution-report experiments/mini_kimi_k3/reports/stage1-source-resolution.json$(stage1_input_inspection_arg) --stage1-remote-readiness-report $REMOTE_READINESS_REPORT" || true
run_rootfs "./experiments/mini_kimi_k3/run.sh completion-audit --preflight-report $PREFLIGHT_REPORT --results-root experiments/mini_kimi_k3/results --run-id $RUN_ID --attempt-id $ATTEMPT_ID --report $COMPLETION_REPORT" || true
step "Review the completion-audit CLI next actions: lines and guidance: details, especially source_deficits for corpus acquisition."
step "Review $COMPLETION_REPORT and confirm which checklist items remain missing."
pause "Press Enter after reviewing the refreshed completion report."

stage "GPU Capacity"
say "The r1 Trainer smoke needs a free GPU before it can prove one optimizer step."
step "If the Monarch GLM-5.2 SGLang service is still holding the B200s, stop or resize it only if you own that runtime decision."
step "After freeing capacity, rerun the r1 smoke readiness gate:"
say "experiments/mini_kimi_k3/run.sh r1-smoke-gpu-readiness --report experiments/mini_kimi_k3/results/r1_smoke_gpu_readiness.json --min-free-gpu-memory-mib 12000"
step "Then rerun the r1 Trainer smoke:"
say "experiments/mini_kimi_k3/run.sh r1-training-smoke --token-manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --report $R1_SMOKE_REPORT --seq-len 4096 --steps 1"
pause "Press Enter when GPU capacity has been handled or deliberately deferred."

stage "Modal Credentials"
say "Use this only if the remote Modal Stage 1 path is the intended corpus route."
say "Credential template: $ENV_EXAMPLE"
say "Required keys: MODAL_TOKEN_ID, MODAL_TOKEN_SECRET, MODAL_PROFILE"
open_url "https://modal.com/settings/tokens"
step "Create or reveal a Modal token pair."
ask MODAL_PROFILE "Modal profile [mini-k3]:"
MODAL_PROFILE="${MODAL_PROFILE:-mini-k3}"
ask_secret MODAL_TOKEN_ID "Paste MODAL_TOKEN_ID:"
ask_secret MODAL_TOKEN_SECRET "Paste MODAL_TOKEN_SECRET:"
write_env MODAL_PROFILE "$MODAL_PROFILE"
write_env MODAL_TOKEN_ID "$MODAL_TOKEN_ID"
write_env MODAL_TOKEN_SECRET "$MODAL_TOKEN_SECRET"
step "Re-run the non-ingesting readiness check:"
say "TORCHTITAN_ROOTFS_NETWORK=networked scripts/rootfs/enter_rootfs.sh -- bash -lc \"cd /workspace/torchtitan && experiments/mini_kimi_k3/run.sh stage1-remote-readiness --env-file $ENV_FILE --report $REMOTE_READINESS_REPORT\""
pause "Press Enter after Modal readiness is ready, or leave it blocked if using local corpus import."

stage "Corpus Route"
say "The full launch requires 5B Kimi-tokenized tokens with provenance and decontamination evidence."
if confirm "Use an already-local corpus export instead of Modal ingestion?"; then
  ask SOURCE_EXPORT "Rootfs-visible path to reviewed Stage 1 export directory:"
  PLANNED_SOURCES=("fineweb-edu" "web-diverse" "code-python" "finemath" "open-web-math" "cosmopedia")
  step "Import reviewed first-party shards for every planned r1 source:"
  for SOURCE_NAME in "${PLANNED_SOURCES[@]}"; do
    run_rootfs "./experiments/mini_kimi_k3/run.sh import-shards --manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --source $SOURCE_NAME --source-dir $SOURCE_EXPORT/tokens/$SOURCE_NAME --link-mode symlink"
  done
elif confirm "Materialize public Hugging Face source inputs locally instead of using Modal?"; then
  warn "This downloads large public parquet inputs locally. It does not decontaminate, tokenize, register shards, or prove launch readiness by itself."
  step "Build local Stage 1 input manifests from the resolved public source report:"
  say "TORCHTITAN_ROOTFS_NETWORK=networked scripts/rootfs/enter_rootfs.sh -- bash -lc \"cd /workspace/torchtitan && experiments/mini_kimi_k3/run.sh materialize-stage1-local --source-resolution-report experiments/mini_kimi_k3/reports/stage1-source-resolution.json --corpus-plan-report experiments/mini_kimi_k3/reports/r1-corpus-plan.json --output-root experiments/mini_kimi_k3/data/stage1-local-inputs --report experiments/mini_kimi_k3/reports/stage1-local-materialize.json --allow-download\""
  step "Then run prepare-stage1-local for each generated <source>-inputs.json after decontamination evidence is available."
else
  warn "Remote ingest is spendful and may submit detached work."
  step "After Modal readiness is ready and spend is authorized, start only the reviewed command:"
  say "TORCHTITAN_ROOTFS_NETWORK=networked scripts/rootfs/enter_rootfs.sh -- bash -lc \"cd /workspace/torchtitan && experiments/mini_kimi_k3/run.sh run-stage1-remote --source-root experiments/mini_kimi_k3/assets/mini-kimi-k3-vizuara --readiness-report $REMOTE_READINESS_REPORT --env-file $ENV_FILE --step ingest_all --allow-spend --report experiments/mini_kimi_k3/reports/stage1-remote-ingest-all.json\""
fi
step "After corpus import/build, rerun:"
say "experiments/mini_kimi_k3/run.sh audit-r1-corpus-plan --manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --corpus-plan experiments/mini_kimi_k3/reports/r1-corpus-plan.json --report $CORPUS_AUDIT_REPORT"
say "experiments/mini_kimi_k3/run.sh corpus-disk-readiness --corpus-plan experiments/mini_kimi_k3/reports/r1-corpus-plan.json --target-path experiments/mini_kimi_k3/data/tokens --report $CORPUS_DISK_READINESS_REPORT --overhead-fraction 0.20"
say "experiments/mini_kimi_k3/run.sh inspect-stage1-inputs --input-manifest <source-inputs.json> --report $STAGE1_INPUT_INSPECTION_REPORT --min-total-tokens 5000000000"
pause "Press Enter after the corpus audit is ready."

stage "Final Preflight And Launch"
say "This stage keeps the existing fail-closed launch guard."
step "Run full preflight:"
say "experiments/mini_kimi_k3/run.sh preflight --mode full --token-manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --evidence-results-root experiments/mini_kimi_k3/results --run-id $RUN_ID --attempt-id $ATTEMPT_ID --oracle-root experiments/mini_kimi_k3/assets/mini-kimi-k3-vizuara --forward-oracle-report .cache/trae-mini-k3-trainer/forward_oracle_r1_candidate_cuda.json --launch-backend-report .cache/trae-mini-k3-trainer/launch_backend_r1_candidate_cuda.json --r1-training-smoke-report $R1_SMOKE_REPORT --r1-corpus-plan-audit-report $CORPUS_AUDIT_REPORT --corpus-disk-readiness-report $CORPUS_DISK_READINESS_REPORT --stage1-source-resolution-report experiments/mini_kimi_k3/reports/stage1-source-resolution.json$(stage1_input_inspection_arg) --stage1-remote-readiness-report $REMOTE_READINESS_REPORT"
if confirm "Did full preflight return status=ready?"; then
  warn "The next command starts the guarded full training attempt."
  if confirm "Start the guarded full Mini Kimi-K3 launch now?"; then
    run_rootfs "./experiments/mini_kimi_k3/run.sh launch --results-root experiments/mini_kimi_k3/results --run-id $RUN_ID --attempt-id $ATTEMPT_ID --mode full --token-manifest experiments/mini_kimi_k3/data/manifest.json --tokens-dir experiments/mini_kimi_k3/data/tokens --seq-len 4096 --forward-oracle-report .cache/trae-mini-k3-trainer/forward_oracle_r1_candidate_cuda.json --launch-backend-report .cache/trae-mini-k3-trainer/launch_backend_r1_candidate_cuda.json --r1-training-smoke-report $R1_SMOKE_REPORT --r1-corpus-plan-audit-report $CORPUS_AUDIT_REPORT --corpus-disk-readiness-report $CORPUS_DISK_READINESS_REPORT --stage1-source-resolution-report experiments/mini_kimi_k3/reports/stage1-source-resolution.json$(stage1_input_inspection_arg) --stage1-remote-readiness-report $REMOTE_READINESS_REPORT"
  else
    SKIPPED+=("guarded full launch")
  fi
else
  SKIPPED+=("full launch; preflight is not ready")
fi
step "Always finish by rerunning completion audit:"
say "experiments/mini_kimi_k3/run.sh completion-audit --preflight-report $PREFLIGHT_REPORT --results-root experiments/mini_kimi_k3/results --run-id $RUN_ID --attempt-id $ATTEMPT_ID --report $COMPLETION_REPORT"

finish
